### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3

### ISSUE THREAD

**Issue by curbsaleem** [pusher/pusher-http-ruby#92] opened 2015-12-31 07:01 UTC
Hi 
I am getting following error. Do you know how i can fix this?

Thanks 

 Parameters: {"utf8"=>"✓", "socket_id"=>"130812.12923904", "chat_message"=>{"name"=>"ffffff", "message"=>"fffff"}, "commit"=>"Send"}
{"utf8"=>"✓", "socket_id"=>"130812.12923904", "chat_message"=>{"name"=>"ffffff", "message"=>"fffff"}, "commit"=>"Send", "action"=>"create", "controller"=>"chat_messages"}
Completed 500 Internal Server Error in 4675ms

OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure):
  app/controllers/chat_messages_controller.rb:10:in `create'

**Comment by zimbatm** [comment] 2015-12-31 11:50
Hi,

can you give me more context. It's probably because the system only supports SSLv3 which had to be deactivated due to the POODLE attack.

What versions of ruby, openssl and operating system are you running ?

**Comment by zimbatm** [comment] 2016-05-15 20:48
Closing because I can't reproduce. Feel free to re-open with more information.

**Closed by zimbatm** 2016-05-15 20:48 UTC
