### ISSUE TITLE
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006,"message":"Connection interrupted (200)"}}}

### ISSUE THREAD

**Issue by FreelancerMasum** [pusher/pusher-http-ruby#147] opened 2019-09-20 12:30 UTC
I am using Rails app with Pusher. I get this message to my browser console:

Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006,"message":"Connection interrupted (200)"}}}

Please help.

![Screenshot from 2019-09-20 18-29-23](https://user-images.githubusercontent.com/55578382/65327009-97edbb00-dbd4-11e9-989b-e57e2968411c.png)

**Comment by annzenkina** [comment] 2019-10-23 11:51
Hey there! I'm sorry that you've experienced troubles. 

When a WebSocket connection is closed without a "close frame", the `pusher-js` library emits an error with code 1006. Usually this is caused by WebSocket-incompatible proxies, which can't close the connection in the correct way. Please take a look at this article for more information: https://support.pusher.com/hc/en-us/articles/360019096474-What-is-meant-by-Channels-error-1006-

After receiving two "Websocket connection failed" messages `pusher-js` will switch to the fallback, for instance, `sockjs`. That means that the user will still receive all the messages but using the other protocol, not Websocket. This is less real-time but should work. 

Hopefully this helps.

**Comment by annzenkina** [comment] 2019-10-23 11:53
I will close the issue for now as it's not the issue with the library. But let us know at support@pusher.com if you have further questions.

**Closed by annzenkina** 2019-10-23 11:53 UTC
